###Test get of service end points for v4 and v2
GET http://localhost:4004/CatalogService

###V2Service

http://localhost:4004/v2/CatalogService

###Read Purchase orders
http://localhost:4004/CatalogService/POs?$top=2&$expand=Items,PARTNER_GUID

###Create new Employee
POST http://localhost:4004/CatalogService/EmployeeSet/02BD2137-0890-1EEA-A6C2-BB55C19787FB
Content-Type: application/json

{ 
            "nameFirst": "Anubhav",
            "nameMiddle": null,
            "nameLast": "Oberoy",
            "nameInitials": null,
            "sex": "M",
            "language": "E",
            "phoneNumber": "+91 (123) 456-7890",
            "email": "anubhav.abap@gmail.com",
            "loginName": "ANUBHAVO",
            "accountNumber": "111222333",
            "bankName": "HDFC bank"
}


###Read Single Employee Which was just created
GET http://localhost:4004/CatalogService/EmployeeSet/$count
Authorization: Basic anubhav:

###Update the salary for the employee
PATCH http://localhost:4004/CatalogService/EmployeeSet/ccf4fb8f-f784-47e2-b40b-94bc2886071f
Content-Type: application/json;IEEE754Compatible=true

{ 
            "salaryAmount": "100000.99",
            "Currency_code": "INR"
}

###Read Single PO - Old syntax works as its not UUID type
GET http://localhost:4004/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC28052')

###Create new PO
POST http://localhost:4004/CatalogService/POs
Content-Type: application/json;IEEE754Compatible=true

{
	"Currency": { "code": "EUR" },
	"GROSS_AMOUNT": "3913.91",
	"NET_AMOUNT": "3289",
	"TAX_AMOUNT": "624.91",
	"PO_ID": 300000300,
	"LIFECYCLE_STATUS": "N",
	"OVERALL_STATUS": "P",
	"PARTNER_GUID_NODE_KEY": "74867AD200E41EDBA5D8B06885B04052"
}

###READ of custom Entity

GET http://localhost:4004/mysrv/ReadEmployeeSrv

###Create Employee with custom handler
POST http://localhost:4004/mysrv/InsertEmployeeSrv
Content-Type: application/json;IEEE754Compatible=true

{           
    "ID": "02BD2137-0890-1EEA-A6C2-BB55C1978969",
    "nameFirst": "Anubhav",
    "nameMiddle": "",
    "nameLast": "Oberoy",
    "nameInitials": "",
    "sex": "M",
    "language": "E",
    "phoneNumber": "+91 (123) 456-7890",
    "email": "anubhav.abap@gmail.com",
    "loginName": "ANUBHAVO",
    "accountNumber": "111222333",
    "bankName": "HDFC bank"
}

###Update using Custom Handler
PUT  http://localhost:4004/mysrv/UpdateEmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C1978969
Content-Type: application/json;IEEE754Compatible=true

{           
    "ID": "02BD2137-0890-1EEA-A6C2-BB55C1978969",
    "nameFirst": "Chrisopher",
    "nameLast": "Columbus"
}

###DELETE The data using Custom Handler
DELETE http://localhost:4004/mysrv/DeleteEmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C1978969


###
GET http://localhost:4004/CatalogService/POs/02BD2137-0890-1EEA-A6C2-BB55C1978999

###Calling action for the Entity
POST http://localhost:4004/CatalogService/POs/02BD2137-0890-1EEA-A6C2-BB55C1978999/CatalogService.boost
Content-Type: application/json

{}

###Read Largest Order in system
GET http://localhost:4004/CatalogService/POs/02BD2137-0890-1EEA-A6C2-BB55C1978999/CatalogService.largestOrder()

###Custom Action
POST http://localhost:4004/v2/CatalogService/POs_boost?ID=02BD2137-0890-1EEA-A6C2-BB55C1978999
Content-Type: application/json

{}

###Calling Function using V2
GET http://localhost:4004/v2/CatalogService/POs_largestOrder?ID=02BD2137-0890-1EEA-A6C2-BB55C1978999
